// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDeDIvYB6_KMMOLNmuM-yEMacaHFX_4UVg',
//     appId: '1:542670031063:web:756a203b468ee62c570892',
//     messagingSenderId: '542670031063',
//     projectId: 'topuprrrbazar-3088d',
//     authDomain: 'topuprrrbazar-3088d.firebaseapp.com',
//     storageBucket: 'topuprrrbazar-3088d.firebasestorage.app',
//     measurementId: 'G-5V50X4CQCS',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDUv2fXkfhlHYwQF-8iy7OrE5dEY7RIgbA',
//     appId: '1:542670031063:android:dad471fc5663a1fc570892',
//     messagingSenderId: '542670031063',
//     projectId: 'topuprrrbazar-3088d',
//     storageBucket: 'topuprrrbazar-3088d.firebasestorage.app',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDeDIvYB6_KMMOLNmuM-yEMacaHFX_4UVg',
//     appId: '1:542670031063:web:5ad055d8dfe1a1d7570892',
//     messagingSenderId: '542670031063',
//     projectId: 'topuprrrbazar-3088d',
//     authDomain: 'topuprrrbazar-3088d.firebaseapp.com',
//     storageBucket: 'topuprrrbazar-3088d.firebasestorage.app',
//     measurementId: 'G-4N3ZRZWJD8',
//   );
// }
